# This is a basic workflow to help you get started with Actions

name: Unit tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 - --preview
          poetry install --with dev,default
      - name: Pytest run
        run: |
          poetry run coverage run --omit="*tests*,*pypoetry*" -m pytest -svv -m "not docker_required"
      - name: Coverage report
        run: |
          poetry run coverage report

  pytest-e2e-with-cluster:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.3
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          curl -sSL https://install.python-poetry.org | python3 - --preview
          poetry install --with dev,default
      - name: Pytest run
        run: |
          poetry run coverage run --omit="*tests*,*pypoetry*" -m pytest -svv -m "docker_required"
      - name: Coverage report
        run: |
          poetry run coverage report